DefaultDep: !!python/unicode 'Layout'
DefaultProj: !!python/unicode 'dsf'
dsf:
  Animation:
  - {ControlName: size_X_spinBox, ReadMethod: value, SetMethod: setValue, Value: 2048}
  - {ControlName: margin_doubleSpinBox, ReadMethod: value, SetMethod: setValue, Value: 0.0}
  - {ControlName: size_Y_spinBox, ReadMethod: value, SetMethod: setValue, Value: 858}
  - {ControlName: scale_doubleSpinBox, ReadMethod: value, SetMethod: setValue, Value: 0.5}
  - {ControlName: quality_spinBox, ReadMethod: value, SetMethod: setValue, Value: 100}
  - {ControlName: format_comboBox, ReadMethod: currentIndex, SetMethod: setCurrentIndex,
    Value: 0}
  - {ControlName: codec_comboBox, ReadMethod: currentIndex, SetMethod: setCurrentIndex,
    Value: 0}
  - {ControlName: fps_spinBox, ReadMethod: value, SetMethod: setValue, Value: 24}
  - {ControlName: start_frame_spinBox, ReadMethod: value, SetMethod: setValue, Value: 101}
  - {ControlName: file_path_lineEdit, ReadMethod: text, SetMethod: setText, Value: '''C:/Users/%username%/Desktop'''}
  - {ControlName: off_screen_checkBox, ReadMethod: isChecked, SetMethod: setChecked,
    Value: 1}
  - {ControlName: font_comboBox, ReadMethod: currentIndex, SetMethod: setCurrentIndex,
    Value: 227}
  - {ControlName: label_color_pushButton, ReadMethod: styleSheet, SetMethod: setStyleSheet,
    Value: '''background-color: rgb(85, 170, 0)'''}
  - {ControlName: value_color_pushButton, ReadMethod: styleSheet, SetMethod: setStyleSheet,
    Value: '''background-color: rgb(255, 255, 0)'''}
  - {ControlName: font_size_comboBox, ReadMethod: currentIndex, SetMethod: setCurrentIndex,
    Value: 7}
  - {ControlName: font_opacity_doubleSpinBox, ReadMethod: value, SetMethod: setValue,
    Value: 1.0}
  - {ControlName: display_mask_checkBox, ReadMethod: isChecked, SetMethod: setChecked,
    Value: 0}
  - {ControlName: board_color_pushButton, ReadMethod: styleSheet, SetMethod: setStyleSheet,
    Value: '''background-color: rgb(113, 113, 113)'''}
  - {ControlName: board_opacity_doubleSpinBox, ReadMethod: value, SetMethod: setValue,
    Value: 1.0}
  Layout:
  - {ControlName: size_X_spinBox, ReadMethod: value, SetMethod: setValue, Value: 2048}
  - {ControlName: margin_doubleSpinBox, ReadMethod: value, SetMethod: setValue, Value: 0.0}
  - {ControlName: size_Y_spinBox, ReadMethod: value, SetMethod: setValue, Value: 858}
  - {ControlName: scale_doubleSpinBox, ReadMethod: value, SetMethod: setValue, Value: 0.5}
  - {ControlName: quality_spinBox, ReadMethod: value, SetMethod: setValue, Value: 100}
  - {ControlName: format_comboBox, ReadMethod: currentIndex, SetMethod: setCurrentIndex,
    Value: 0}
  - {ControlName: codec_comboBox, ReadMethod: currentIndex, SetMethod: setCurrentIndex,
    Value: 0}
  - {ControlName: fps_spinBox, ReadMethod: value, SetMethod: setValue, Value: 24}
  - {ControlName: start_frame_spinBox, ReadMethod: value, SetMethod: setValue, Value: 1}
  - {ControlName: file_path_lineEdit, ReadMethod: text, SetMethod: setText, Value: !!python/unicode 'C:/Users/%username%/Desktop'}
  - {ControlName: off_screen_checkBox, ReadMethod: isChecked, SetMethod: setChecked,
    Value: true}
  - {ControlName: font_comboBox, ReadMethod: currentIndex, SetMethod: setCurrentIndex,
    Value: 0}
  - {ControlName: label_color_pushButton, ReadMethod: styleSheet, SetMethod: setStyleSheet,
    Value: !!python/unicode 'background-color: rgb(139, 141, 255);'}
  - {ControlName: value_color_pushButton, ReadMethod: styleSheet, SetMethod: setStyleSheet,
    Value: !!python/unicode 'background-color: rgb(189, 98, 123);'}
  - {ControlName: font_size_comboBox, ReadMethod: currentIndex, SetMethod: setCurrentIndex,
    Value: 7}
  - {ControlName: font_opacity_doubleSpinBox, ReadMethod: value, SetMethod: setValue,
    Value: 1.0}
  - {ControlName: display_mask_checkBox, ReadMethod: isChecked, SetMethod: setChecked,
    Value: false}
  - {ControlName: board_color_pushButton, ReadMethod: styleSheet, SetMethod: setStyleSheet,
    Value: !!python/unicode '''background-color: rgb(113, 113, 113)'''}
  - {ControlName: board_opacity_doubleSpinBox, ReadMethod: value, SetMethod: setValue,
    Value: 1.0}
  Lighting:
  - {ControlName: size_X_spinBox, ReadMethod: value, SetMethod: setValue, Value: 2048}
  - {ControlName: size_Y_spinBox, ReadMethod: value, SetMethod: setValue, Value: 858}
  - {ControlName: margin_doubleSpinBox, ReadMethod: value, SetMethod: setValue, Value: 0.0}
  - {ControlName: scale_doubleSpinBox, ReadMethod: value, SetMethod: setValue, Value: 0.5}
  - {ControlName: quality_spinBox, ReadMethod: value, SetMethod: setValue, Value: 100}
  - {ControlName: format_comboBox, ReadMethod: currentIndex, SetMethod: setCurrentIndex,
    Value: 0}
  - {ControlName: codec_comboBox, ReadMethod: currentIndex, SetMethod: setCurrentIndex,
    Value: 0}
  - {ControlName: fps_spinBox, ReadMethod: value, SetMethod: setValue, Value: 24}
  - {ControlName: start_frame_spinBox, ReadMethod: value, SetMethod: setValue, Value: 101}
  - {ControlName: file_path_lineEdit, ReadMethod: text, SetMethod: setText, Value: '''C:/Users/%username%/Desktop'''}
  - {ControlName: off_screen_checkBox, ReadMethod: isChecked, SetMethod: setChecked,
    Value: 1}
  - {ControlName: font_comboBox, ReadMethod: currentIndex, SetMethod: setCurrentIndex,
    Value: 227}
  - {ControlName: label_color_pushButton, ReadMethod: styleSheet, SetMethod: setStyleSheet,
    Value: '''background-color: rgb(85, 170, 0)'''}
  - {ControlName: value_color_pushButton, ReadMethod: styleSheet, SetMethod: setStyleSheet,
    Value: '''background-color: rgb(255, 255, 0)'''}
  - {ControlName: font_size_comboBox, ReadMethod: currentIndex, SetMethod: setCurrentIndex,
    Value: 7}
  - {ControlName: font_opacity_doubleSpinBox, ReadMethod: value, SetMethod: setValue,
    Value: 1.0}
  - {ControlName: display_mask_checkBox, ReadMethod: isChecked, SetMethod: setChecked,
    Value: 0}
  - {ControlName: board_color_pushButton, ReadMethod: styleSheet, SetMethod: setStyleSheet,
    Value: '''background-color: rgb(113, 113, 113)'''}
  - {ControlName: board_opacity_doubleSpinBox, ReadMethod: value, SetMethod: setValue,
    Value: 1.0}
  VFX:
  - {ControlName: size_X_spinBox, ReadMethod: value, SetMethod: setValue, Value: 2048}
  - {ControlName: size_Y_spinBox, ReadMethod: value, SetMethod: setValue, Value: 858}
  - {ControlName: margin_doubleSpinBox, ReadMethod: value, SetMethod: setValue, Value: 0.0}
  - {ControlName: scale_doubleSpinBox, ReadMethod: value, SetMethod: setValue, Value: 0.5}
  - {ControlName: quality_spinBox, ReadMethod: value, SetMethod: setValue, Value: 100}
  - {ControlName: format_comboBox, ReadMethod: currentIndex, SetMethod: setCurrentIndex,
    Value: 0}
  - {ControlName: codec_comboBox, ReadMethod: currentIndex, SetMethod: setCurrentIndex,
    Value: 0}
  - {ControlName: fps_spinBox, ReadMethod: value, SetMethod: setValue, Value: 24}
  - {ControlName: start_frame_spinBox, ReadMethod: value, SetMethod: setValue, Value: 101}
  - {ControlName: file_path_lineEdit, ReadMethod: text, SetMethod: setText, Value: '''C:/Users/%username%/Desktop'''}
  - {ControlName: off_screen_checkBox, ReadMethod: isChecked, SetMethod: setChecked,
    Value: 1}
  - {ControlName: font_comboBox, ReadMethod: currentIndex, SetMethod: setCurrentIndex,
    Value: 227}
  - {ControlName: label_color_pushButton, ReadMethod: styleSheet, SetMethod: setStyleSheet,
    Value: '''background-color: rgb(85, 170, 0)'''}
  - {ControlName: value_color_pushButton, ReadMethod: styleSheet, SetMethod: setStyleSheet,
    Value: '''background-color: rgb(255, 255, 0)'''}
  - {ControlName: font_size_comboBox, ReadMethod: currentIndex, SetMethod: setCurrentIndex,
    Value: 7}
  - {ControlName: font_opacity_doubleSpinBox, ReadMethod: value, SetMethod: setValue,
    Value: 1.0}
  - {ControlName: display_mask_checkBox, ReadMethod: isChecked, SetMethod: setChecked,
    Value: 0}
  - {ControlName: board_color_pushButton, ReadMethod: styleSheet, SetMethod: setStyleSheet,
    Value: '''background-color: rgb(113, 113, 113)'''}
  - {ControlName: board_opacity_doubleSpinBox, ReadMethod: value, SetMethod: setValue,
    Value: 1.0}
